[env]
AWS_PROFILE = "medic"
AWS_REGION = "ap-northeast-1"
STATE_BUCKET = "terraform-homeosapiens-staging-ap-northeast-1"

[tools]
go = "1.25.3"
pipx = "1.8.0"
terraform = "1.14.0"
terragrunt = "0.93.10"
ansible = "13.0.0"
