# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-fufood-staging-ap-east-2"
    dynamodb_table = "terraform-locks-ap-east-2"
    encrypt        = true
    key            = "./terraform.tfstate"
    profile        = "fufood"
    region         = "ap-east-2"
  }
}
