# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-homeosapiens-staging-ap-northeast-1"
    dynamodb_table = "terraform-locks-ap-northeast-1"
    encrypt        = true
    key            = "./terraform.tfstate"
    profile        = "medic"
    region         = "ap-northeast-1"
  }
}
