# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

provider "aws" {
  region  = "ap-northeast-1"
  profile = "fufood"
}

provider "aws" {
  region  = "ap-northeast-1"
  profile = "fufood"
  alias   = "tokyo"
}
